<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\KineticReports.Core\KineticReports.Core.csproj" />
    <ProjectReference Include="..\..\Core\KineticReports.Layout\KineticReports.Layout.csproj" />
  </ItemGroup>

</Project>
