<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\KineticReports.Core\KineticReports.Core.csproj" />
    <ProjectReference Include="..\..\Core\KineticReports.Engine\KineticReports.Engine.csproj" />
    <ProjectReference Include="..\..\Core\KineticReports.Layout\KineticReports.Layout.csproj" />
    <ProjectReference Include="..\..\Export\KineticReports.Export.Html\KineticReports.Export.Html.csproj" />
  </ItemGroup>

</Project>
