<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

 <ItemGroup>
   <ProjectReference Include="..\..\Core\KineticReports.Core\KineticReports.Core.csproj" />
    <ProjectReference Include="..\..\Viewer\KineticReports.Viewer.Blazor\KineticReports.Viewer.Blazor.csproj" />
    <ProjectReference Include="..\..\Plugins\KineticReports.Samples.Plugins\KineticReports.Samples.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\sample-reports.seed.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
